#!/bin/bash
git config --global user.email "nobody@concourse-ci.org"
git config --global user.name "Concourse"

cd new-result

#
# Add and commit changes.
#
git add ./
git commit -m "Perform analysis (success)."
